### ISSUE TITLE
Volumes for modules, themes, files, etc

### ISSUE THREAD

**Issue by acao** [gabeos/docker-openatrium#2]
How would you like to approach volumization, or is this just documentation? Going to play with this myself shortly.

**Comment by gabeos** [comment]
So, if you look at the readme under MIGRATE_SITES_TO, you'll see how I attempted to bootstrap a system to handle moving the sites around so you could mount them on your local host, or in an edit volume or something to work on them directly during development, but really I think that that was all based on a misunderstanding of volumes.. if you play around with it at all, do not do so with anything you'd care about losing. 

Currently the Dockerfile declares /data and /var/www/html/sites as volumes. I forget if /data is used at all, but the sites folder is a volumes, and AFAIK (although I am very much not a PHP/Drupal dev) all the installation/local changes are in the sites directory. I would recommend using a data container with the image, so via docker-compose:

``` yaml
oadata:
    image: gabeos/docker-openatrium
    entrypoint: echo
    command: "OA Data Container"
oa:
    image: gabeos/docker-openatrium
    volumes_from: oadata
...
```
